// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "fressh-react-native-uniffi-russh.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_com_uniffirussh_ReactNativeUniffiRusshModule and fressh_reactnativeuniffirussh
// by comparing the whole line here.
/*
Java_com_uniffirussh_ReactNativeUniffiRusshModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return fressh_reactnativeuniffirussh::multiply(a, b);
}
*/

// Installer coming from ReactNativeUniffiRusshModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_com_uniffirussh_ReactNativeUniffiRusshModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    using JCallInvokerHolder = facebook::react::CallInvokerHolder;

    auto holderLocal = facebook::jni::make_local(callInvokerHolderJavaObj);
    auto holderRef = facebook::jni::static_ref_cast<JCallInvokerHolder::javaobject>(holderLocal);
    auto* holderCxx = holderRef->cthis();
    auto jsCallInvoker = holderCxx->getCallInvoker();
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);

    return fressh_reactnativeuniffirussh::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_uniffirussh_ReactNativeUniffiRusshModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return fressh_reactnativeuniffirussh::cleanupRustCrate(*runtime);
}