export * from './connection-diagnostic-types';
export {
	diagnosticEvents,
	type ActiveConnectionEvent,
	type AutoConnectActiveConnectionMissingEvent,
	type AutoConnectActiveConnectionSelectedEvent,
	type AutoConnectActiveConnectionShellConnectedEvent,
	type AutoConnectActiveConnectionShellFailedEvent,
	type AutoConnectActiveConnectionShellStartedEvent,
	type AutoConnectActiveConnectionTmuxAttachFailedEvent,
	type AutoConnectLatestShellMissingEvent,
	type AutoConnectLatestShellSelectedEvent,
	type AutoConnectSavedEntryConnectConnectedEvent,
	type AutoConnectSavedEntryConnectFailedEvent,
	type AutoConnectSavedEntryConnectStartedEvent,
	type AutoConnectSavedEntryConnectThrewEvent,
	type AutoConnectSavedEntryConnectTmuxAttachFailedEvent,
	type AutoConnectSavedEntryRetryStartedEvent,
	type AutoConnectSavedEntryRetryThrewEvent,
	type ConnectionDiagnosticEventBase,
	type DiagnosticDisconnectedEvent,
	type DiagnosticDisconnectFailedEvent,
	type KeyMissingEvent,
	type KeyResolvedEvent,
	type ManualDiagnosticEvent,
	type ManualDiagnosticFailedEvent,
	type ManualDiagnosticSavedEntryMissingEvent,
	type ManualDiagnosticTailscaleAttentionClearedEvent,
	type ManualDiagnosticTailscaleAttentionEvent,
	type ManualDiagnosticTimeoutEvent,
	type ManualDiagnosticTmuxAttachFailedEvent,
	type ManualDiagnosticWarningEvent,
	type ReconnectAttemptConnectedEvent,
	type ReconnectAttemptFailedEvent,
	type ReconnectAttemptStartedEvent,
	type ReconnectEvent,
	type ReconnectRetryScheduledEvent,
	type ReconnectStartBlockedEvent,
	type ReconnectStartedEvent,
	type ReconnectStoppedEvent,
	type ReconnectTimeoutEvent,
	type SavedEntryConnectEvent,
	type SavedEntryInvalidTmuxSettingsEvent,
	type SavedEntryMissingEvent,
	type SavedEntrySelectedEvent,
	type SshConnectConnectedEvent,
	type SshConnectFailedEvent,
	type SshConnectProgressEvent,
	type SshConnectStartedEvent,
	type SshShellConnectedEvent,
	type SshShellFailedEvent,
	type SshShellStartedEvent,
	type SshShellTmuxAttachFailedEvent,
	type TailscaleEnsureReadyEvent,
	type TailscaleRecoveryResultEvent,
} from './connection-diagnostic-events';
export { serializeConnectionDiagnosticError } from './connection-diagnostic-redaction';
export {
	createConnectionDiagnosticRecorder,
	connectionDiagnosticRecorder,
} from './connection-diagnostic-recorder';
export { formatConnectionDiagnosticPrompt } from './connection-diagnostic-prompt';
