export const KEYBOARD_TARGET_ACTION_IDS = [
	'OPEN_MAIN_MENU',
	'OPEN_ADVANCED_KEYBOARD',
	'OPEN_BROWSER_KEYBOARD',
] as const;

export const WORKMUX_KEYBOARD_ACTION_IDS = [
	'WORKMUX_FOCUS_CLAUDE',
	'WORKMUX_FOCUS_GIT',
	'WORKMUX_FOCUS_CODEX',
	'WORKMUX_FOCUS_BASH',
	'WORKMUX_FOCUS_PREV',
	'WORKMUX_FOCUS_NEXT',
	'WORKMUX_FOCUS_TOGGLE_GIT_BASH',
	'WORKMUX_NAV_PREV',
	'WORKMUX_NAV_NEXT',
	'WORKMUX_NAV_PREV_ALL',
	'WORKMUX_NAV_NEXT_ALL',
] as const;

export const WORKMUX_KEYBOARD_COMPATIBILITY_ACTION_IDS = [
	'CYCLE_WORKMUX_STATUS',
] as const;

export const KNOWN_ACTION_IDS = [
	'ROTATE_KEYBOARD',
	'OPEN_KEYBOARD_SETTINGS',
	...KEYBOARD_TARGET_ACTION_IDS,
	'TOGGLE_COMMAND_MENU',
	'WORKMUX_NAV_SCOPE_ACTIVE',
	'WORKMUX_NAV_SCOPE_VISIBLE',
	'WORKMUX_NAV_SCOPE_ALL',
	'FIT_TERMINAL_TO_DEVICE',
	'RESTART_CODEX',
	'DEBUG_CONNECTION_IN_CODEX',
	'REFLOW_TERMINAL',
	'OPEN_COMMANDER',
	'OPEN_NEW_WORKTREE_WORKSPACE',
	'OPEN_CLOSE_WORKTREE_WORKSPACE',
	'OPEN_SKILL_SELECTOR',
	'OPEN_BROWSER_ACTIONS',
	'OPEN_REPO_FEATURE_REQUEST',
	'OPEN_WISPR_TEXT_EDITOR',
	'PASTE_CLIPBOARD',
	'COPY_SELECTION',
	'OPEN_HOST_DIFFITY',
	'OPEN_HOST_URL_WINDOW',
	'OPEN_HOST_URL_DEV_SERVER',
	'OPEN_HOST_URL_STORYBOOK',
	'OPEN_HOST_URL_APP',
	'OPEN_HOST_DETECTED_AUTO',
	'OPEN_HOST_DETECTED_PICK',
	'EDIT_HOST_URL_WINDOW',
	'EDIT_HOST_URL_DEV_SERVER',
	'EDIT_HOST_URL_STORYBOOK',
	'EDIT_HOST_URL_APP',
	...WORKMUX_KEYBOARD_ACTION_IDS,
	...WORKMUX_KEYBOARD_COMPATIBILITY_ACTION_IDS,
] as const;

export const CONFIG_SUPPORTED_ACTION_IDS = KNOWN_ACTION_IDS;

export type KnownActionId = (typeof KNOWN_ACTION_IDS)[number];
export type KeyboardTargetActionId =
	(typeof KEYBOARD_TARGET_ACTION_IDS)[number];
export type WorkmuxKeyboardActionId =
	| (typeof WORKMUX_KEYBOARD_ACTION_IDS)[number]
	| (typeof WORKMUX_KEYBOARD_COMPATIBILITY_ACTION_IDS)[number];
export type ActionId = KnownActionId | (string & {});
